plugins {
    id 'java-library'
    id 'maven-publish'
    id 'net.neoforged.moddev' version '2.0.107'
    id 'idea'
    id 'java'
}

tasks.named('wrapper', Wrapper).configure {
    distributionType = Wrapper.DistributionType.BIN
}

version = mod_version
group = mod_group_id

repositories {
    maven {
        // location of the maven that hosts JEI files since January 2023
        name = "Jared's maven"
        url = "https://maven.blamejared.com/"
    }
    maven {
        // location of a maven mirror for JEI files, as a fallback
        name = "ModMaven"
        url = "https://modmaven.dev"
    }

    maven {
        url "https://www.cursemaven.com"
        content {
            includeGroup "curse.maven"
        }
    }
}

base {
    archivesName = mod_id
}

java.toolchain.languageVersion = JavaLanguageVersion.of(17)

neoForge {
    version = project.neo_version

    parchment {
        mappingsVersion = project.parchment_mappings_version
        minecraftVersion = project.parchment_minecraft_version
    }

    runs {
        client {
            client()
            systemProperty 'neoforge.enabledGameTestNamespaces', project.mod_id
        }

        server {
            server()
            programArgument '--nogui'
            systemProperty 'neoforge.enabledGameTestNamespaces', project.mod_id
        }

        gameTestServer {
            type = "gameTestServer"
            systemProperty 'neoforge.enabledGameTestNamespaces', project.mod_id
        }

        data {
            data()

            programArguments.addAll '--mod', project.mod_id, '--all', '--output', file('src/generated/resources/').getAbsolutePath(), '--existing', file('src/main/resources/').getAbsolutePath()
        }

        configureEach {
            systemProperty 'forge.logging.markers', 'REGISTRIES'
            logLevel = org.slf4j.event.Level.DEBUG
        }
    }

    mods {
        "${mod_id}" {
            sourceSet(sourceSets.main)
        }
    }
}

sourceSets {
    main {
        resources {
            srcDirs += 'src/generated/resources'
        }
    }
}

configurations {
    runtimeClasspath.extendsFrom localRuntime
}

dependencies {
    compileOnly("mezz.jei:jei-${minecraft_version}-common-api:${jei_version}")
    compileOnly("mezz.jei:jei-${minecraft_version}-neoforge-api:${jei_version}")
    runtimeOnly("mezz.jei:jei-${minecraft_version}-neoforge:${jei_version}")

    implementation "curse.maven:jade-324717:${jade_id}"
    implementation "curse.maven:biomes-o-plenty-220318:${bop_id}"
    implementation "curse.maven:terrablender-neoforge-940057:${terra_id}"
    implementation "curse.maven:glitchcore-955399:${glitch_id}"
    implementation "curse.maven:patchouli-306770:${patchouli_id}"
    //implementation "curse.maven:endremastered-404183:${endrem_id}"
    //implementation "curse.maven:dynamictrees-252818:${dt_id}"

}

var generateModMetadata = tasks.register("generateModMetadata", ProcessResources) {
    var replaceProperties = [
            minecraft_version      : minecraft_version,
            minecraft_version_range: minecraft_version_range,
            neo_version            : neo_version,
            loader_version_range   : loader_version_range,
            mod_id                 : mod_id,
            mod_name               : mod_name,
            mod_license            : mod_license,
            mod_version            : mod_version,
            mod_authors            : mod_authors,
            mod_description        : mod_description
    ]
    inputs.properties replaceProperties
    expand replaceProperties
    from "src/main/templates"
    into "build/generated/sources/modMetadata"
}

sourceSets.main.resources.srcDir generateModMetadata
neoForge.ideSyncTask generateModMetadata

publishing {
    publications {
        register('mavenJava', MavenPublication) {
            from components.java
        }
    }
    repositories {
        maven {
            url "file://${project.projectDir}/repo"
        }
    }
}

tasks.withType(JavaCompile).configureEach {
    options.encoding = 'UTF-8'
}

idea {
    module {
        downloadSources = true
        downloadJavadoc = true
    }
}

tasks.register("copyRunDataConfig", Copy) {
    from("run/config/grasses")
    into("src/generated/resources/data/grasses/config")
    include("additional_drops.toml")
}

tasks.named("processResources") {
    dependsOn("copyRunDataConfig")
}

def modVersion = project.findProperty('mod_version') ?: 'unknown_version'
def generatedJavaDir = layout.buildDirectory.dir("generated/sources/version").get().asFile
def outputFilePath = "${generatedJavaDir}/net/night/grasses/Version.java"

sourceSets.main.java.srcDir generatedJavaDir

tasks.register("generateVersionClass") {
    outputs.file(outputFilePath)

    doLast {
        def packageName = 'net.night.grasses'
        def outputDir = new File("${generatedJavaDir}", packageName.replace('.', '/'))
        outputDir.mkdirs()

        def file = new File(outputDir, "Version.java")
        file.text = """
            package ${packageName};

            public final class Version {
                public static final String MOD_VERSION = "${modVersion}";
            }
        """
        println "Generated Version.java with MOD_VERSION = ${modVersion}"
    }
}


tasks.named("compileJava") {
    dependsOn(tasks.named("generateVersionClass"))
    doFirst {
        logger.lifecycle("Starting compileJava task, ensuring generateVersionClass ran first")
    }
}
